import express from "express";
import Camp from "../models/Camp.js";
import ItemPriority from "../models/ItemPriority.js";
import { authenticate, authorize } from "../middleware/authMiddleware.js";
import { PostFloodMLService } from "../utils/postFloodMLService.js";

const router = express.Router();

const buildMlItemPriorityData = (camp, result) => {
  const priorityValues = { Low: 1, Medium: 2, High: 3 };
  const averagePriority =
    (priorityValues[result.food_priority] +
      priorityValues[result.water_priority] +
      priorityValues[result.medicine_priority] +
      priorityValues[result.sanitary_priority]) /
    4;

  let overallUrgency = "Low";
  if (averagePriority >= 2.5) overallUrgency = "High";
  else if (averagePriority >= 1.5) overallUrgency = "Medium";

  return {
    camp_id: camp._id,
    food_priority: result.food_priority,
    water_priority: result.water_priority,
    medicine_priority: result.medicine_priority,
    sanitary_priority: result.sanitary_priority,
    recommended_food_qty: Math.max(
      0,
      Math.round((camp.population || 0) * 6 - (camp.food_available || 0)),
    ),
    recommended_water_qty: Math.max(
      0,
      Math.round((camp.population || 0) * 10 - (camp.water_available || 0)),
    ),
    recommended_medicine_qty: Math.max(
      0,
      Math.round((camp.population || 0) * 0.5 - (camp.medicine_available || 0)),
    ),
    recommended_sanitary_qty: Math.max(
      0,
      Math.round((camp.population || 0) * 2 - (camp.sanitary_available || 0)),
    ),
    overall_urgency: overallUrgency,
    notes: "Generated by post-flood camp need ML model",
  };
};

router.post(
  "/generate/:campId",
  authenticate,
  authorize("admin", "disaster_officer"),
  async (req, res) => {
    try {
      const camp = await Camp.findById(req.params.campId);
      if (!camp) return res.status(404).json({ error: "Camp not found" });

      const result = await PostFloodMLService.predictCampNeeds(camp);

      const itemPriority = await ItemPriority.findOneAndUpdate(
        { camp_id: camp._id },
        buildMlItemPriorityData(camp, result),
        { upsert: true, new: true },
      );

      res.json({ status: "success", data: itemPriority });
    } catch (error) {
      res
        .status(500)
        .json({
          error: "Failed to generate item priorities",
          details: error.message,
        });
    }
  },
);

router.get("/camp/:campId", authenticate, async (req, res) => {
  try {
    const itemPriority = await ItemPriority.findOne({
      camp_id: req.params.campId,
    }).sort({ updatedAt: -1 });
    if (!itemPriority)
      return res.status(404).json({ error: "No item priority found" });
    res.json({ status: "success", data: itemPriority });
  } catch (error) {
    res.status(500).json({ error: "Failed to fetch", details: error.message });
  }
});

router.put(
  "/:id",
  authenticate,
  authorize("admin", "disaster_officer"),
  async (req, res) => {
    try {
      const updated = await ItemPriority.findByIdAndUpdate(
        req.params.id,
        req.body,
        { new: true },
      );
      if (!updated) return res.status(404).json({ error: "Not found" });
      res.json({ status: "success", data: updated });
    } catch (error) {
      res
        .status(500)
        .json({ error: "Failed to update", details: error.message });
    }
  },
);

router.get("/", authenticate, async (req, res) => {
  try {
    const { include_seed, mine } = req.query;
    const campFilter = {};
    if (mine === "true" && req.user) campFilter.created_by = req.user._id;
    else if (include_seed !== "true") campFilter.created_by = { $ne: null };

    const camps = await Camp.find(campFilter).select("_id");
    const campIds = camps.map((c) => c._id);

    let items = [];
    if (campIds.length > 0) {
      items = await ItemPriority.find({ camp_id: { $in: campIds } }).populate(
        "camp_id",
        "camp_name population priority_level",
      );
    }

    res.json({ status: "success", data: items });
  } catch (error) {
    res.status(500).json({ error: "Failed to fetch", details: error.message });
  }
});

export { router as itemPriorityRouter };
