const PRIORITY_VALUES = { Low: 1, Medium: 2, High: 3 };

const shortage = (required, available) =>
  Math.max(0, Math.round(required - (available || 0)));

const dispatchPriority = (mlPriority, recommendedQty) =>
  recommendedQty === 0 ? "Low" : mlPriority || "Low";

const overallUrgency = (priorities) => {
  const averagePriority =
    priorities.reduce(
      (total, priority) => total + (PRIORITY_VALUES[priority] || 1),
      0,
    ) / priorities.length;

  if (averagePriority >= 2.5) return "High";
  if (averagePriority >= 1.5) return "Medium";
  return "Low";
};

export const buildMlItemPriorityData = (camp, result) => {
  const population = camp.population || 0;
  const recommendedFoodQty = shortage(population * 6, camp.food_available);
  const recommendedWaterQty = shortage(population * 10, camp.water_available);
  const recommendedMedicineQty = shortage(
    population * 0.5,
    camp.medicine_available,
  );
  const recommendedSanitaryQty = shortage(
    population * 2,
    camp.sanitary_available,
  );

  const foodPriority = dispatchPriority(
    result.food_priority,
    recommendedFoodQty,
  );
  const waterPriority = dispatchPriority(
    result.water_priority,
    recommendedWaterQty,
  );
  const medicinePriority = dispatchPriority(
    result.medicine_priority,
    recommendedMedicineQty,
  );
  const sanitaryPriority = dispatchPriority(
    result.sanitary_priority,
    recommendedSanitaryQty,
  );

  return {
    camp_id: camp._id,
    food_priority: foodPriority,
    water_priority: waterPriority,
    medicine_priority: medicinePriority,
    sanitary_priority: sanitaryPriority,
    recommended_food_qty: recommendedFoodQty,
    recommended_water_qty: recommendedWaterQty,
    recommended_medicine_qty: recommendedMedicineQty,
    recommended_sanitary_qty: recommendedSanitaryQty,
    overall_urgency: overallUrgency([
      foodPriority,
      waterPriority,
      medicinePriority,
      sanitaryPriority,
    ]),
    notes: "Generated by post-flood camp need ML model",
  };
};
